name: CI Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run test.sh
      run: bash test.sh
      
    - name: Deploy to Ubuntu via SSH
      uses: appleboy/ssh-action@master
      with:
      	host: ${{ secrets.SSH_HOST }}
      	username: ${{ secrets.SSH_USER }}
      	key: ${{ secrets.SSH_KEY }}
      	script: |
      	  cd WeatherWebapp
      	  git pull origin main
      	  pkill -f http.server || true
      	  nohup python3 -m http.server 8080 &
      	  echo "✅️ Deployed and server restarted"
